---
- name : Configure gitaly servers
  hosts: gitaly
  become: yes
  become_user: root
  vars:
    proxy_env:
      http_proxy: http://{{ hostvars[inventory_hostname].proxy }}:3128
      https_proxy: http://{{ hostvars[inventory_hostname].proxy }}:3128
      ftp_proxy: http://{{ hostvars[inventory_hostname].proxy }}:3128
  environment: "{{ proxy_env }} "
  tasks :

    - name: Add gitlab pkg repo
      shell: 'curl https://packages.gitlab.com/install/repositories/gitlab/gitlab-ee/script.deb.sh | bash'

    - name: Creates directory
      file:
        path: /etc/gitlab
        state: directory
        owner: root
        group: root
        mode: 0600

    - name: Place GitLab omnibus configuration file with gitaly role
      template:
        src: gitlab.rb.gitaly.j2
        dest: /etc/gitlab/gitlab.rb
        owner: root
        group: root
        mode: 0600

    - name: Install gitlab omnibus
      apt: name={{item}} state=present
      with_items:
        - gitlab-ee=12.0.0-ee.0

    - name: Activate changes
      shell: "gitlab-ctl reconfigure"

    - name: Creates storage directories
      file:
        path: "{{ item }}"
        state: directory
        owner: git
        group: git
        mode: 0700
      with_items:
        - "/mnt/gitlab"
        - "/mnt/gitlab/default"
        - "/mnt/gitlab/default/repositories"
        - "/mnt/gitlab/storage1"
        - "/mnt/gitlab/storage1/repositories"

    - name: Transfer generated secrets from first appserver
      copy:
        src: /tmp/gitlab-secrets.json
        dest: /etc/gitlab/gitlab-secrets.json
        owner: root
        group: root
        mode: 0600

    - name: Activate changes
      shell: "gitlab-ctl reconfigure"

    - name: Restart services
      shell: "gitlab-ctl restart"
