---
- name : Configure PGbouncer servers
  hosts: pgbouncer
  become: yes
  become_user: root
  vars:
    proxy_env:
      http_proxy: http://{{ hostvars[inventory_hostname].proxy }}:3128
      https_proxy: http://{{ hostvars[inventory_hostname].proxy }}:3128
      ftp_proxy: http://{{ hostvars[inventory_hostname].proxy }}:3128
  environment: "{{ proxy_env }} "
  tasks :
  
    - name: Add gitlab pkg repo
      shell: 'curl https://packages.gitlab.com/install/repositories/gitlab/gitlab-ee/script.deb.sh | bash'

    - name: Creates gitlab config directory
      file:
        path: /etc/gitlab
        state: directory
        owner: root
        group: root
        mode: 0600

    - name: Place GitLab omnibus configuration file with PGbouncer Role
      template:
        src: gitlab.rb.pgbouncer.j2
        dest: /etc/gitlab/gitlab.rb
        owner: root
        group: root
        mode: 0600

    - name: Install gitlab omnibus
      apt: name={{item}} state=present
      with_items:
        - gitlab-ee=12.0.0-ee.0

    - name: Creates consul directories
      file:
        path: "{{ item }}"
        state: directory
      with_items:
        - /var/opt/gitlab/
        - /var/opt/gitlab/consul

    - name: Place pgpassword file
      template:
        src: pgpass.j2
        dest: /var/opt/gitlab/consul/.pgpass

    - name: Place database ini file
      template:
        src: databases.ini.j2
        dest: /var/opt/gitlab/consul/databases.ini
        owner: root
        group: root
        mode: 0755

    - name: Activate changes
      shell: "gitlab-ctl reconfigure"

    - name: Restart services
      shell: "gitlab-ctl restart"
