---
- name : Configure frontend application servers
  hosts: frontend
  become: yes
  serial: 1
  become_user: root
  vars:
    proxy_env:
      http_proxy: http://{{ hostvars[inventory_hostname].proxy }}:3128
      https_proxy: http://{{ hostvars[inventory_hostname].proxy }}:3128
      ftp_proxy: http://{{ hostvars[inventory_hostname].proxy }}:3128
  environment: "{{ proxy_env }} "
  tasks :

    - name: Modify /etc/environment
      lineinfile:
        path: /etc/environment
        line: LC_ALL="en_US.UTF-8"

    - name: Install Aptitude
      apt:
        update_cache: yes
        name: aptitude

    - name: Modify /etc/environment
      lineinfile:
        path: /etc/environment
        line: LC_ALL="en_US.UTF-8"

    - name: Add gitlab pkg repo
      shell: 'curl https://packages.gitlab.com/install/repositories/gitlab/gitlab-ee/script.deb.sh | bash'

    - name: Creates gitlab config directory
      file:
        path: /etc/gitlab
        state: directory
        owner: root
        group: root
        mode: 0600

    - name: Place GitLab omnibus configuration file
      template:
        src: gitlab.rb.frontend.j2
        dest: /etc/gitlab/gitlab.rb
        owner: root
        group: root
        mode: 0600

    - name: Disable automigrations
      shell: touch /etc/gitlab/skip-auto-reconfigure

    - name: Install gitlab omnibus
      apt: name={{item}} state=present
      with_items:
        - gitlab-ee=12.0.0-ee.0

    - name: Transfer generated secrets from first appserver
      copy:
        src: /tmp/gitlab-secrets.json
        dest: /etc/gitlab/gitlab-secrets.json
        owner: root
        group: root
        mode: 0600
      when: hostvars[inventory_hostname].role == "slave"

    - name: Active changes
      shell: "gitlab-ctl reconfigure"

    - name: Pause for 1 minute to give reconfigure time
      pause:
        minutes: 1

    - name: Restart services
      shell: "gitlab-ctl restart"
