---
- name : Configure bastion servers
  hosts: security
  become: yes
  become_user: root
  tasks :
    - name: Install Aptitude
      apt:
        update_cache: yes
        name: aptitude

    - name: Install Squid
      apt:
        name: squid
        update_cache: yes

    - name: Allow connections to squid
      lineinfile:
        dest: /etc/squid/squid.conf
        regexp: '^http_access deny all'
        line: 'http_access allow all'
    - name: always restart squid
      service: name=squid state=restarted

    - name: copy generated key with owner and permissions
      copy:
        src: /tmp/mykey.pem
        dest: /tmp/mykey.pem
        owner: root
        group: root
        mode: 0600

    - name: copy ansible config to bastion hosts
      copy:
        src: .ansible.cfg
        dest: /root/.ansible.cfg
        owner: root
        group: root
        mode: 0644
